<a href="https://colab.research.google.com/github/s-dabral/Specialization_Training/blob/main/Placeholders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# importing tensorflow
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# creating nodes in computation graph
a = tf.placeholder(tf.int32, shape=(3,1))
b = tf.placeholder(tf.int32, shape=(1,3))
c = tf.matmul(a,b)

# running computation graph
with tf.Session() as sess:
	print(sess.run(c, feed_dict={a:[[3],[2],[1]], b:[[1,2,3]]}))

Instructions for updating:
non-resource variables are not supported in the long term


[[3 6 9]
 [2 4 6]
 [1 2 3]]
